# Generated by Django 5.1 on 2024-08-22 15:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Case_Title', models.CharField(max_length=255)),
                ('date_time_of_incident', models.DateTimeField()),
                ('date_time_of_report', models.DateTimeField()),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_contact', models.CharField(max_length=20)),
                ('complainant_physical_address', models.CharField(max_length=255)),
                ('complainant_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('complainant_date_of_birth', models.DateField(blank=True, null=True)),
                ('suspect_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('suspect_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('suspect_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('suspect_date_of_birth', models.DateField(blank=True, null=True)),
                ('is_victim_same_as_complainant', models.BooleanField(default=True)),
                ('victim_name', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('victim_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('victim_date_of_birth', models.DateField(blank=True, null=True)),
                ('location_of_incident', models.CharField(max_length=255)),
                ('type_of_incident', models.CharField(choices=[('Theft', 'Theft'), ('Assault', 'Assault'), ('Traffic Accident', 'Traffic Accident'), ('Other', 'Other')], max_length=100)),
                ('statement_of_incident', models.TextField()),
                ('key_witness_name', models.CharField(blank=True, max_length=255, null=True)),
                ('key_witness_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('key_witness_physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('key_witness_digital_address', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_statement', models.TextField()),
                ('suspect_statement', models.TextField()),
                ('witness_statement', models.TextField()),
                ('additional_witnesses', models.JSONField(blank=True, default=list)),
                ('reporting_officer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_officer_badge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_officer_rank', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_officer_station', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_officer_division', models.CharField(blank=True, max_length=255, null=True)),
                ('charges_filed', models.TextField(blank=True, null=True)),
                ('legal_actions_taken', models.TextField(blank=True, null=True)),
                ('assigned_investigator', models.CharField(blank=True, max_length=255, null=True)),
                ('case_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Closed', 'Closed')], max_length=50, null=True)),
                ('follow_up_required', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('mugshot', models.FileField(blank=True, null=True, upload_to='mugshots/')),
                ('fingerprint', models.FileField(blank=True, null=True, upload_to='fingerprints/')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NewOfficerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('officer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone_contact', models.IntegerField(unique=True)),
                ('officer_address', models.CharField(max_length=250)),
                ('officer_current_rank', models.CharField(choices=[('Constable', 'Constable'), ('Lance Corporal', 'Lance Corporal'), ('Corporal', 'Corporal'), ('Sergeant', 'Sergeant'), ('District Sergeant Major', 'District Sergeant Major'), ('Inspector', 'Inspector'), ('Regional Sergeant Major', 'Regional Sergeant Major'), ('Chief Inspector', 'Chief Inspector'), ('Assistant Superintendent of Police', 'Assistant Superintendent of Police'), ('Deputy Superintendent of Police', 'Deputy Superintendent of Police'), ('Superintendent of Police', 'Superintendent of Police'), ('Chief Superintendent', 'Chief Superintendent'), ('Assistant Commissioner of Police', 'Assistant Commissioner of Police'), ('Deputy Commissioner of Police', 'Deputy Commissioner of Police'), ('Commissioner of Police', 'Commissioner of Police'), ('Inspector General of Police', 'Inspector General of Police')], max_length=250)),
                ('officer_current_station', models.CharField(max_length=250)),
                ('officer_staff_ID', models.CharField(max_length=250, unique=True)),
                ('officer_qualification', models.CharField(choices=[('WS', 'WASSCE'), ('DG', 'DEGREE'), ('MS', 'MASTERS'), ('PH', 'PHD')], max_length=250)),
                ('officer_date_of_birth', models.DateField()),
                ('officer_operations_region', models.CharField(choices=[('GA', 'Greater Accra'), ('AR', 'Ahafo Region'), ('ARR', 'Ashanti Region'), ('BR', 'Bono Region'), ('BER', 'Bono East Region'), ('CR', 'Central Region'), ('ER', 'Eastern Region'), ('NER', 'North East Region'), ('NR', 'Northern Region'), ('OR', 'Oti Region'), ('SR', 'Savannah Region'), ('UER', 'Upper East Region'), ('UWR', 'Upper West Region'), ('VR', 'Volta Region'), ('WR', 'Western Region'), ('WNR', 'Western North Region')], max_length=250)),
                ('officer_operations_department', models.CharField(choices=[('CID', 'Criminal Investigation Department [CID]'), ('MTTD', 'Motor Traffic and Transport Directorate [MTTD]'), ('DOVVSU', 'Domestic Violence and Victim Support Unit [DOVVSU]'), ('The Police College', 'The Police College'), ('Other Training Institutions', 'Other Training Institutions'), ('W&H', 'Works & Housing Department'), ('PRD', 'Public Relations Department'), ('MH', 'Medical – Hospital'), ('Marine Ports & Railways', 'Marine Ports & Railways'), ('Community Policing', 'Community Policing')], max_length=250)),
                ('officer_profile_image', models.ImageField(blank=True, null=True, upload_to='profileImages/')),
                ('officer_stationRank', models.CharField(choices=[('DC', 'District Commander'), ('DIVC', 'Divisional Commander'), ('SO', 'Station Officer'), ('DSO', 'Deputy Station Officer'), ('SSI', 'Station Sergeants and Inspector'), ('OO', 'Other Officer/Constables')], max_length=100)),
                ('officer_Operationsdistrict', models.CharField(choices=[('GA', 'Greater Accra'), ('AR', 'Ahafo Region'), ('ARR', 'Ashanti Region'), ('BR', 'Bono Region'), ('BER', 'Bono East Region'), ('CR', 'Central Region'), ('ER', 'Eastern Region'), ('NER', 'North East Region'), ('NR', 'Northern Region'), ('OR', 'Oti Region'), ('SR', 'Savannah Region'), ('UER', 'Upper East Region'), ('UWR', 'Upper West Region'), ('VR', 'Volta Region'), ('WR', 'Western Region'), ('WNR', 'Western North Region')], max_length=250)),
                ('password', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
