# Generated by Django 5.1 on 2024-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_ID',
            field=models.CharField(default=255, max_length=255),
            preserve_default=False,
        ),
    ]
