# Generated by Django 5.1 on 2024-08-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_case_case_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='witness_statement',
            new_name='key_witness_statement',
        ),
    ]
