# Generated by Django 5.1 on 2024-08-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_rename_witness_statement_case_key_witness_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='additional_witnesses',
        ),
    ]
