# Generated by Django 5.1 on 2024-08-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_remove_case_additional_witnesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='complainant_physical_address',
            new_name='complainant_address',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='complainant_digital_address',
            new_name='complainant_identification_card',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='key_witness_digital_address',
            new_name='key_witness_address',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='key_witness_physical_address',
            new_name='key_witness_identification_card',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='suspect_digital_address',
            new_name='suspect_address',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='suspect_physical_address',
            new_name='suspect_identification_card',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='victim_digital_address',
            new_name='victim_address',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='victim_physical_address',
            new_name='victim_identification_card',
        ),
        migrations.AddField(
            model_name='case',
            name='complainant_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='key_witness_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='key_witness_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='suspect_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
